### ISSUE TITLE
Firebase Authentication Implementation

### ISSUE THREAD

**Issue by 1719pankaj** [1719pankaj/Dank-Memes-2#2]
Firebase Auth using google, email, and phone Number

**Comment by GeorgeET15** [comment]
Hi Sir/Ma'am

I can implement this for you. Please assign me. Thank you

**Comment by 1719pankaj** [comment]
Use your own Firebase account, I'll work out the kinks with the SHA keys at the time of Merge.
I am still in the midst of writing up the Contributing Mandate, so here's what you need to know
All the onboarding is done using Shared Intents and the project uses a lot of libraries.
Please use a separate branch, It'll make my life so much easier.
All the best.

**Comment by GeorgeET15** [comment]
ok sir
