### ISSUE TITLE
Fix UI inconsistencies

### ISSUE THREAD

**Issue by 1719pankaj** [1719pankaj/Dank-Memes-2#4]
All the FABs and buttons' colors do not compliment the theme. and the color resource file is very bloated.

**Comment by SiddyDevelops** [comment]
@1719pankaj I would like to resolve the issue, please assign it to me. Thank you.

**Comment by 1719pankaj** [comment]
Sure yeah 
The buttons and FABs are coloured blue and they don't really go with the over-all theme 
Just fix it.
And maybe look around if you find anything fixable.

**Comment by SiddyDevelops** [comment]
@1719pankaj Sir I have generated a PR #9. Please Review it. Also please add ```Hacktober-accepted``` label to my PR. Thank you.
